// Layout test for the built-in breadboards (generated by scripts/gen-breadboards.mjs): hole counts,
// strips of 5, rails in groups of 5 with a gap, every hole on the 10 px grid, and boards that
// wires route over. A change here must match the real board layout it models.
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { isBoard, validateModule, type ModuleDef } from './module.ts'

const dir = join(import.meta.dirname, '..', '..', 'modules')
const load = (id: string): ModuleDef => {
  const r = validateModule(JSON.parse(readFileSync(join(dir, `${id}.json`), 'utf8')))
  if (!r.ok) throw new Error(`${id}: ${r.errors.join('; ')}`)
  return r.module
}
const count = (m: ModuleDef) => m.holes!.reduce((n, g) => n + g.at.length, 0)

// id, name, total holes, 5-hole strips, rails, holes per rail
const boards = [
  ['breadboard-full', 'Full breadboard (830)', 830, 126, 4, 50],
  ['breadboard-half', 'Half breadboard (400)', 400, 60, 4, 25],
  ['breadboard-mini', 'Mini breadboard (170)', 170, 34, 0, 0],
  ['breadboard-tiny', 'Tiny breadboard (25)', 25, 5, 0, 0],
  ['power-rail-strip', 'Power rail strip', 50, 0, 2, 25],
] as const

describe('built-in breadboards', () => {
  for (const [id, name, holes, strips, rails, railLength] of boards)
    it(`${id}: ${holes} holes, ${strips} strips of 5, ${rails} rails of ${railLength}`, () => {
      const m = load(id)
      expect(m.name).toBe(name)
      expect(m.category).toBe('Prototyping')
      expect(isBoard(m)).toBe(true)
      expect(m.pins).toEqual([])
      expect(count(m)).toBe(holes)
      const railGroups = m.holes!.filter((g) => g.rail)
      const stripGroups = m.holes!.filter((g) => !g.rail)
      expect(stripGroups).toHaveLength(strips)
      for (const g of stripGroups) expect(g.at).toHaveLength(5)
      expect(railGroups).toHaveLength(rails)
      for (const g of railGroups) expect(g.at).toHaveLength(railLength)
      for (const g of m.holes!) for (const [x, y] of g.at) expect([x % 10, y % 10]).toEqual([0, 0])
    })

  it('full board: rails run in groups of 5 with a one-hole gap', () => {
    const m = load('breadboard-full')
    for (const name of ['top+', 'top-', 'bottom-', 'bottom+']) {
      const rail = m.holes!.find((g) => g.name === name)!
      const steps = rail.at.slice(1).map(([x], i) => x - rail.at[i][0])
      expect(steps).toEqual(Array.from({ length: 49 }, (_, i) => ((i + 1) % 5 === 0 ? 20 : 10)))
      expect(rail.at[0][0]).toBe(50)
    }
    expect(m.holes!.find((g) => g.name === 'top+')!.rail).toBe('+')
    expect(m.holes!.find((g) => g.name === 'top-')!.at[0]).toEqual([50, 30])
  })

  it('full board: column 12 is rows a-e above the channel and f-j below it', () => {
    const m = load('breadboard-full')
    expect(m.holes!.find((g) => g.name === 'c12-top')).toEqual({ name: 'c12-top', label: '12 a-e', at: [[140, 60], [140, 70], [140, 80], [140, 90], [140, 100]] })
    expect(m.holes!.find((g) => g.name === 'c12-bot')!.at).toEqual([[140, 130], [140, 140], [140, 150], [140, 160], [140, 170]])
    expect(m.size).toEqual({ w: 68, h: 23 })
  })

  it('half board rails start at column 1', () => {
    const m = load('breadboard-half')
    expect(m.holes!.find((g) => g.name === 'top+')!.at[0]).toEqual([30, 20])
    expect(m.holes!.find((g) => g.name === 'c1-top')!.at[0]).toEqual([30, 60])
  })
})
