// Regression test for the Raspberry Pi Pico family: the 40-pin header and the 3-pin SWD port
// must list their pins in the physical order of the official Raspberry Pi pinout diagrams (see
// each module's `source`), seen from the component side with the USB connector at the top.
// A wrong pin is worse than a missing board, so a change here must be re-checked against the
// source. The modules are generated by scripts/gen-picos.mjs.
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { isSpacer, layoutModule, validateModule, type ModuleDef } from './module.ts'
import { designatorPrefix } from '../editor/ops.ts'

const dir = join(import.meta.dirname, '..', '..', 'modules')
const load = (id: string): ModuleDef => {
  const r = validateModule(JSON.parse(readFileSync(join(dir, `${id}.json`), 'utf8')))
  if (!r.ok) throw new Error(`${id}: ${r.errors.join('; ')}`)
  return r.module
}

// Silkscreen text (label ?? name). Left: physical pins 1..20; right: 40..21; bottom: SWD port
// left to right. All five boards share this header.
const LEFT = ['GP0', 'GP1', 'GND', 'GP2', 'GP3', 'GP4', 'GP5', 'GND', 'GP6', 'GP7', 'GP8', 'GP9', 'GND', 'GP10', 'GP11', 'GP12', 'GP13', 'GND', 'GP14', 'GP15']
const RIGHT = ['VBUS', 'VSYS', 'GND', '3V3_EN', '3V3(OUT)', 'ADC_VREF', 'GP28/ADC2', 'AGND', 'GP27/ADC1', 'GP26/ADC0', 'RUN', 'GP22', 'GND', 'GP21', 'GP20', 'GP19', 'GP18', 'GND', 'GP17', 'GP16']
const BOTTOM = ['SWCLK', 'GND', 'SWDIO']

const boards = ['rpi-pico', 'rpi-pico-h', 'rpi-pico-w', 'rpi-pico-2', 'rpi-pico-2-w']

describe('Raspberry Pi Pico family keeps the physical header order', () => {
  it('pin numbers 1-40 map to the rows as on the board', () => {
    // Pin n on the left row is LEFT[n - 1]; pin n on the right row is RIGHT[40 - n].
    const byNumber = (n: number) => (n <= 20 ? LEFT[n - 1] : RIGHT[40 - n])
    expect([1, 3, 20, 21, 30, 33, 35, 36, 37, 39, 40].map(byNumber)).toEqual(
      ['GP0', 'GND', 'GP15', 'GP16', 'RUN', 'AGND', 'ADC_VREF', '3V3(OUT)', '3V3_EN', 'VSYS', 'VBUS'],
    )
  })

  for (const id of boards) {
    const m = load(id)
    it(`${id}: rows match the source pinout, on pitch, facing each other`, () => {
      expect(m.id).toBe(id)
      expect(m.category).toBe('Microcontrollers')
      expect(m.source).toMatch(/^https:\/\/datasheets\.raspberrypi\.com\//)
      expect(m.art?.pinLabels).toBe('inside')
      expect(designatorPrefix(m)).toBe('U')
      expect(m.pins.some(isSpacer)).toBe(false)
      const lay = layoutModule(m)
      const want = { left: LEFT, right: RIGHT, bottom: BOTTOM }
      for (const side of ['left', 'right', 'bottom'] as const) {
        const pins = lay.pins.filter((p) => p.side === side)
        expect(pins.map((p) => p.label ?? p.name)).toEqual(want[side])
        const along = (p: (typeof pins)[number]) => (side === 'bottom' ? p.edge.x : p.edge.y)
        pins.forEach((p, i) => i && expect(along(p) - along(pins[i - 1])).toBe(10))
      }
      expect(lay.pins.filter((p) => p.side === 'top')).toEqual([])
      // Both rows start at the same height, as on the real header; the SWD port is centered.
      expect(lay.pins.find((p) => p.side === 'left')!.edge.y).toBe(lay.pins.find((p) => p.side === 'right')!.edge.y)
      expect(lay.pins.find((p) => p.name === 'GND DBG')!.edge.x).toBe(lay.w / 2)
      expect(lay.w % 10).toBe(0)
    })

    it(`${id}: pin types and grounds`, () => {
      const pins = m.pins.flatMap((p) => (isSpacer(p) ? [] : [p]))
      const byName = new Map(pins.map((p) => [p.name, p]))
      expect(byName.get('VBUS')).toMatchObject({ type: 'power_in', supply: '5V' })
      expect(byName.get('VSYS')).toMatchObject({ type: 'power_in', supply: '5V/3.7V/3V3' })
      expect(byName.get('3V3(OUT)')).toMatchObject({ type: 'power_out', supply: '3V3' })
      for (const n of ['3V3_EN', 'RUN', 'ADC_VREF', 'SWCLK']) expect(byName.get(n)?.type).toBe('input')
      expect(byName.get('AGND')?.type).toBe('ground')
      for (let i = 0; i <= 28; i++) {
        const gp = pins.find((p) => p.name === `GP${i}` || p.name.startsWith(`GP${i}/`))
        if (i >= 23 && i <= 25) expect(gp).toBeUndefined() // GP23-25 are on-board only
        else expect(gp?.type ?? 'io').toBe('io')
      }
      // Every digital GND (header and debug port) is one net; AGND stays separate.
      const gnds = pins.filter((p) => p.type === 'ground' && p.name !== 'AGND').map((p) => p.name)
      expect(gnds).toEqual(['GND', 'GND 2', 'GND 3', 'GND 4', 'GND 5', 'GND 6', 'GND 7', 'GND DBG'])
      expect(m.internal).toEqual([gnds])
      for (const p of pins) if (p.type === 'power_in' || p.type === 'power_out') expect(p.supply).toBeTruthy()
    })
  }
})
